ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "elo" integer DEFAULT 1200 NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "wins" integer DEFAULT 0 NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "losses" integer DEFAULT 0 NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "draws" integer DEFAULT 0 NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "games_played" integer DEFAULT 0 NOT NULL;
